FROM ubuntu:20.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    valgrind \
    clang \
    libcurl4-openssl-dev \
    clang-format

WORKDIR /cwd

CMD make && ./weer
