name: Build weer Docker images
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
      - Makefile
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - mini
          - dev
    steps:
      - uses: actions/checkout@v2
      - run: docker login https://heyajulia-docker-weer-docker.bintray.io --username heyajulia --password ${{ secrets.BINTRAY_API_KEY }}
      - run: docker build -f Dockerfile.${{ matrix.tag }} -t heyajulia-docker-weer-docker.bintray.io/weer/weer:${{ matrix.tag }} .
      - run: docker push heyajulia-docker-weer-docker.bintray.io/weer/weer:${{ matrix.tag }}
