name: Build weer for macOS
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
      - Makefile
jobs:
  build:
    name: Build weer
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: make
      - name: Upload to Bintray
        run: >
          curl -T out/weer
          -u heyajulia:${{ secrets.BINTRAY_API_KEY }}
          -H "X-Bintray-Package: weer-macos"
          -H "X-Bintray-Version: $(out/weer --version 2>&1)"
          https://api.bintray.com/content/heyajulia/weer-binaries/weer
